@startuml
!define RECTANGLE class

rectangle "Host (puerto 80)" {
  component Traefik {
    [EntryPoint web :80 "charizard.localhost"]
  }
}

rectangle "app_network (bridge)" {
  component backend{
  [backend :3000 "mewtwo.localhost"]
  }
  component database{
  [Neo4j DB "snorlax.localhost"]
  }
  
}

Traefik --> backend 
backend --> database
@enduml
